In [ ]:
import numpy as np # array creation, arry elements are seperated by white space

arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
l = [10,20,30]
print(l)
print(type(l)) # elemsta are sepearted by ,

[10, 20, 30]
<class 'list'>


In [ ]:
arr = np.array([10, 1.1,20,30, "BLR"]) # if we try to create a array with dufferent datatype , it coverts the entire array to a higher data type array
print(arr)

['10' '1.1' '20' '30' 'BLR']


In [ ]:
#Operations on Array

a1 = np.array([10,20,30])
print(a1)

a2 = a1+2


print(a2)

[10 20 30]
[12 22 32]


In [ ]:
#Operations on List

a1 =[10,20,30]
print(a1)
a2 = a1*3
print(a2)

[10, 20, 30]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [ ]:
# memory consumption

import sys

l = [10,20,30]
print(sys.getsizeof(l))

a = np.array([10,20,30])
print(a.itemsize)
print(a.nbytes)

88
8
24


In [ ]:
# creating ndarray

a = np.array([10,20,30,40])

print(a)
print(type(a))
print(a.ndim)

[10 20 30 40]
<class 'numpy.ndarray'>
1


In [ ]:
#o dim array
a= np.array(44)
print(a)
print(type(a))
print(a.ndim)

44
<class 'numpy.ndarray'>
0


In [ ]:
#2 dim array
a= np.array([[10,20,30]])
print(a)
print(type(a))
print(a.ndim)

[[10 20 30]]
<class 'numpy.ndarray'>
2


In [ ]:
#2 dim array
a= np.array([[[10,20,30]]])
print(a)
print(type(a))
print(a.ndim)

[[[10 20 30]]]
<class 'numpy.ndarray'>
3


In [ ]:
#n dimm array

n = int(input("enter the dim"))

a= np.array([10,20,30], ndmin=n)
print(a)
print(a.ndim)

enter the dim7
[[[[[[[10 20 30]]]]]]]
7


In [ ]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print(a.ndim)

[[10 20 30]
 [40 50 60]]
2


In [ ]:
a = np.array([[10,20,30],[40,50,60]])

print(a)

print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(a.min())
print(a.max())
print(a.sum())

print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.mean())
print(a.std())
print(a.var())

[[10 20 30]
 [40 50 60]]
(2, 3)
6
int64
8
48
10
60
210
[50 70 90]
[ 60 150]
35.0
17.07825127659933
291.6666666666667


In [ ]:
# create a nd array with all zeros

a = np.zeros(4)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[0. 0. 0. 0.]
float64
1
(4,)


In [ ]:
# create a nd array with all zeros

a = np.zeros((4,3), dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int64
2
(4, 3)


In [ ]:
# create a nd array with all zeros

a = np.ones((4,3), dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int64
2
(4, 3)


In [ ]:
# create a nd array with all zeros

a = np.ones((4,3), dtype='float') * 7
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
float64
2
(4, 3)


In [ ]:
#arange function
a = np.arange(10)
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [ ]:
#arange function
a = np.arange(2,10,2,dtype = 'float')
print(a)
print(a.ndim)
print(a.shape)

[2. 4. 6. 8.]
1
(4,)


In [ ]:

#linspace- generate numbers in linear space

a = np.linspace(1,2,5)
print(a)

[1.   1.25 1.5  1.75 2.  ]


In [ ]:
# Create a 1D array using linspace
linear_space = np.linspace(1, 10, 12)  # Generates 12 numbers between 1 and 10

# Reshape the 1D array into a 2D array (e.g., 3 rows and 4 columns)
two_d_array = linear_space.reshape(3, 4)

print(two_d_array)

[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


In [ ]:
#Matrix

mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)
print(type(mat))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [ ]:
# transpose of a mtrix
mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)

trans = mat.T
print(mat)
print(trans)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# identity matrix

mat = np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.diag([10,20,30])
print(a)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [ ]:
# random numbers

a = np.random.random(10)
print(a)

[0.10981565 0.61255507 0.69165976 0.58706504 0.29290614 0.12693574
 0.07623645 0.83101348 0.98919298 0.29651471]


In [ ]:
a = np.random.random((3,3,))
print(a)

[[0.68005548 0.43992827 0.15062832]
 [0.02683189 0.73178775 0.1087211 ]
 [0.91036725 0.30111957 0.16945403]]


In [ ]:
r = np.random.randint(11,150, size =5)
print(r)

[142 118 143 104  83]


In [ ]:
r = np.random.uniform(1,100, size=10)
print(r)

[89.2085604  57.91191596 99.78890461 81.07388874 67.17999009 93.85729551
 39.85608367 76.11054083 87.29562846 17.73468697]


In [ ]:
#choosing random numbers
arr_2d=np.arange(1,101).reshape(10,10)
print(arr_2d)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
#choosing random column numbers

In [ ]:
#shuffling the array
a=np.arange(10)
print(a)
np.random.shuffle(a)# shuffle the original array
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 3 8 2 4 5 9 7 1 6]


In [ ]:
# permutation
a=np.random.permutation(10)
print(a)

[5 3 7 1 9 2 6 4 0 8]


In [ ]:
# permutations with 2D array
array_3d=np.arange(0,20).reshape(4,5)
print(arr_2d)
a=np.random.permutation(array_3d)
print(a)
print(arr_2d)# original array still remains same

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
array_2d=np.arange(0,20).reshape(4,5)
print(arr_2d)
num_rows=array_2d.shape[0]
shuffled_index=np.random.permutation(num_rows) # row shuffling
print(shuffled_index)
shuffled_array=array_2d[shuffled_index] # column shuffling
print(shuffled_array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[0 1 2 3]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
#grouping and splitting---not completed
array_1d=np.arange(10)
print(array_1d)
array_2d=np.arange(0,18).reshape(3,6)
print(array_2d)
array_3d=np.arange(18,36).reshape(3,6)
print(array_3d)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
# stacking

In [ ]:
# vertical staking


In [ ]:
# horizontal staking

In [ ]:
#np.split


In [3]:
import numpy as np
arr1=np.arange(20)
print(arr1)
arr2=np.arange(20,40)
print(arr2)
print(np.split(arr1,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


In [4]:
#
array=np.array([(["Apple", "Microsoft", "Amazon", "Google"],
["Cupertino", "Redmond", "Seattle", "Mountain View"])])
print(array)


[[['Apple' 'Microsoft' 'Amazon' 'Google']
  ['Cupertino' 'Redmond' 'Seattle' 'Mountain View']]]


In [7]:
# Horizontal split
companies,cities=np.hsplit(array,2)
print(companies)
print(cities)

[[['Apple' 'Microsoft' 'Amazon' 'Google']]]
[[['Cupertino' 'Redmond' 'Seattle' 'Mountain View']]]
