In [ ]:
print("Hello World")

Hello World


In [4]:
import numpy as np # array creation array elements are saperated by space

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
ls=[1,2,"B",4,5] # list accepts different type of data
print(ls)
print(type(ls))

[1, 2, 'B', 4, 5]
<class 'list'>


In [5]:
arr=np.array([1,2,"B",4,5]) # if we try to array with different data types,it will convert to same type
print(arr)
print(type(arr))

['1' '2' 'B' '4' '5']
<class 'numpy.ndarray'>


In [8]:
# operations on array
a1=np.array([10,20,30])
a2=a1*2
print(a2)
a3=a1/2
print(a3)
a4=a1+5
print(a4)

[20 40 60]
[ 5. 10. 15.]
[15 25 35]


In [12]:
# memory consumption
import sys
ls=[1,2,3]
print(sys.getsizeof(ls))

a=np.array([1,2,3])
print(a.itemsize)
print(a.size)
print(a.itemsize*a.size)

88
8
3
24


In [14]:
# creating ndarray
a=np.array([10,20,30])
print(a)
print(type(a))
print(a.ndim)

[10 20 30]
<class 'numpy.ndarray'>
1


In [16]:
a=np.array(10)# 0 dimension array
print(a)
print(type(a))
print(a.ndim)

10
<class 'numpy.ndarray'>
0


In [17]:
a=np.array([[[10]]]) # based on [] dymension of array
print(a)
print(type(a))
print(a.ndim)

[[[10]]]
<class 'numpy.ndarray'>
3


In [25]:
# n dimentsion array
n=int(input('enter the dimension'))
a=np.array([1,2,3], ndmin=n)
print(a)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.min())
print(a.max())
print(a.sum())
print(a.nbytes)

enter the dimension6
[[[[[[1 2 3]]]]]]
6
int64
8
1
3
6
24


In [30]:
# create a nd array with all zero's
a=np.zeros((4,3),dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int64
2
(4, 3)


In [31]:
# create a nd array with all ones's
a=np.ones((4,3),dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int64
2
(4, 3)


In [32]:
# create a nd array with all ones's
a=np.ones((4,3),dtype='int') *7
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
int64
2
(4, 3)


In [33]:
# a range function
a=np.arange(10)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
1
(10,)


In [34]:
# a range function
a=np.arange(2,10,2)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[2 4 6 8]
int64
1
(4,)


In [37]:
# lnspace generate numbers in linear space
a=np.linspace(1,10,12)
b=a.reshape(4,3)

print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(b)
print(b.dtype)
print(b.ndim)
print(b.shape)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
float64
1
(12,)
[[ 1.          1.81818182  2.63636364]
 [ 3.45454545  4.27272727  5.09090909]
 [ 5.90909091  6.72727273  7.54545455]
 [ 8.36363636  9.18181818 10.        ]]
float64
2
(4, 3)


In [41]:
# matrix
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print(mat.dtype)
print(type(mat))
print(mat.ndim)
print(mat.shape)
trans=mat.T # transpose of matrix
print(trans)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
<class 'numpy.matrix'>
2
(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [42]:
a=np.diag([10,20,30])
print(a)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [46]:
# random numbers
a=np.random.random(10) # all numbers generate between 0 and 1
print(a)

[0.72913956 0.24209787 0.01802469 0.43453827 0.71913596 0.06985803
 0.1352894  0.65395179 0.75422627 0.75533466]


In [51]:
a=np.random.randint(11,150,5) # all numbers generate between 11 and 150
print(a)

[128  32  19  84  18]


In [52]:
# floating numbers
r=np.random.uniform(1,10,5) # all numbers generate between 1 and 10
print(r)

[8.16649181 5.75897366 3.33144382 4.13929242 3.20316426]
